module.exports = {
    AUDIO_MIMETYPES: [
        'audio/aac',
        'audio/basic',
        'audio/L24',
        'audio/mp4',
        'audio/mpeg',
        'audio/ogg',
        "audio/vnd.rn-realaudio",
        'audio/vnd.wave',
        'audio/vorbis',
        'audio/webm',
        'audio/x-ms-wax',
        'audio/x-ms-wma',
    ],
    DOC_MIMETYPES: [
        'application/gzip',
        'application/msword',
        'application/pdf',
        'application/vnd.ms-excel',
        'application/vnd.ms-powerpoint',
        'application/vnd.oasis.opendocument.graphics',
        'application/vnd.oasis.opendocument.presentation',
        'application/vnd.oasis.opendocument.spreadsheet',
        'application/vnd.oasis.opendocument.text',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/x-rar-compressed',
        'application/x-tar',
        'application/zip,',
    ],
    MAX_AUDIO_SIZE: 15 * 1024 * 1024, // 15 MB
    MAX_DOC_SIZE: 10 * 1024 * 1024, // 10 MB
    MAX_PHOTO_SIZE: 5 * 1024 * 1024, // 5 MB
    MAX_VIDEO_SIZE: 200 * 1024 * 1024, // 200 MB
    PHOTO_MIMETYPES: [
        'image/gif',
        'image/jpeg',
        'image/png',
        'image/pjpeg',
        'image/svg+xml',
        'image/tiff',
        'image/vnd.microsoft.icon',
        'image/vnd.wap.wbmp',
        'image/webp',
    ],
    VIDEO_MIMETYPES: [
        'video/3gpp',
        'video/3gpp2',
        'video/mp4',
        'video/mpeg',
        'video/ogg',
        'video/quicktime',
        'video/x-ms-wmv',
        'video/x-flv',
        'video/webm',
    ],
};